googlegenomics/utils-java

pom.xml, src/main/java/com/google/cloud/genomics/utils/Contig.java
Make Contig member instances final, to prevent unintended mutations.
Mark the project as Java 1.7 as Contig uses this level of compatibility.
=> Make Contig members final. 

pom.xml, src/main/java/com/google/cloud/genomics/utils/Contig.java, src/main/java/com/google/cloud/genomics/utils/Paginator.java, src/test/java/com/google/cloud/genomics/utils/PaginatorTest.java
Prior to this change, cluster compute jobs attempting to shard the variants data will see any records that span a shard boundary in both shards.  In some cases this might be okay, in others it is not.
Also changed the filter parameter in getContigsInVariantSet from a boolean to an enum to indicate its behavior.
=> Client-side shard fix

src/main/java/com/google/cloud/genomics/utils/Contig.java, src/main/java/com/google/cloud/genomics/utils/Paginator.java, src/test/java/com/google/cloud/genomics/utils/PaginatorTest.java
Now that we are doing client-side filtering for strict shard boundaries, we need to check that we are requesting the field that the filter will require and return a useful error if not.
Also increased the default number of bases per shard.  This yields a reasonable number of tasks for sharded jobs running over the whole human genome.
=> Provide a better error for client-side shard filtering.

pom.xml
This reverts commit 587bf079beac16e66bcd201028d0474b7f963e19.
Revert "[maven-release-plugin] prepare release google-genomics-utils-v1beta2-0.28"
This reverts commit 462e8feaf26455bf6c49d1d127f7032f874a113a.
=> Undoing my messed up version release so I can start over.

src/main/java/com/google/cloud/genomics/grpc/ReadUtils.java, src/test/java/com/google/cloud/genomics/grpc/ReadUtilsTest.java
This allows a user to get the referenceSequence (currently unpopulated) of a Read assuming its MD tag has been populated properly.
=> Adding MD tag parser for v1 Reads

.travis.yml
This will catch javadoc lint issues at pull request time.
See also https://github.com/googlegenomics/dataflow-java/issues/109
=> Configure Travis CI to check java8.

.gitignore, pom.xml, src/main/java/com/google/cloud/genomics/utils/Contig.java, src/main/java/com/google/cloud/genomics/utils/GenomicsFactory.java, src/main/java/com/google/cloud/genomics/utils/GenomicsUtils.java, src/main/java/com/google/cloud/genomics/utils/Paginator.java, src/main/java/com/google/cloud/genomics/utils/ShardUtils.java, src/test/java/com/google/cloud/genomics/utils/ContigTest.java, src/test/java/com/google/cloud/genomics/utils/GenomicsUtilsITCase.java, src/test/java/com/google/cloud/genomics/utils/IntegrationTestHelper.java, src/test/java/com/google/cloud/genomics/utils/ShardUtilsITCase.java, src/test/java/com/google/cloud/genomics/utils/ShardUtilsTest.java
Logic to shard genomic ranges should be all in one place to be reused by both dataflow and spark.  Its also important to ensure that the full collection of shards is shuffled so that parallel requests will be distributed across the dataset.
This pull request is part 1 of many parts to refactor some logic currently in dataflow-java down into utils-java so that it can be more widely re-used.  Since this code may change yet again, sending these pull requests to a branch for now instead of master.
=> Refactor genomic range sharing into utils-java.

pom.xml, src/main/java/com/google/cloud/genomics/utils/GenomicsFactory.java, src/main/java/com/google/cloud/genomics/utils/grpc/ReadStreamIterator.java, src/main/java/com/google/cloud/genomics/utils/grpc/VariantStreamIterator.java, src/test/java/com/google/cloud/genomics/utils/GenomicsFactoryITCase.java, src/test/java/com/google/cloud/genomics/utils/GenomicsFactoryTest.java, src/test/java/com/google/cloud/genomics/utils/GenomicsUtilsITCase.java, src/test/java/com/google/cloud/genomics/utils/IntegrationTestHelper.java, src/test/java/com/google/cloud/genomics/utils/ShardUtilsITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/ReadStreamIteratorITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/VariantStreamIteratorITCase.java
Also updated auth in the streamers to use user credentials.
Fixes 
* https://github.com/googlegenomics/utils-java/issues/34
* https://github.com/googlegenomics/utils-java/issues/35
* https://github.com/googlegenomics/dataflow-java/issues/122
I also moved a few GenomicsFactory unit tests that check retries into an ITCase file since they incur some time to run.
=> Refactor streamers from dataflow-java for reuse by spark.

src/main/java/com/google/cloud/genomics/utils/GenomicsFactory.java, src/main/java/com/google/cloud/genomics/utils/grpc/Channels.java, src/main/java/com/google/cloud/genomics/utils/grpc/ReadStreamIterator.java, src/main/java/com/google/cloud/genomics/utils/grpc/VariantStreamIterator.java, src/test/java/com/google/cloud/genomics/utils/GenomicsFactoryTest.java, src/test/java/com/google/cloud/genomics/utils/IntegrationTestHelper.java, src/test/java/com/google/cloud/genomics/utils/grpc/ReadStreamIteratorITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/VariantStreamIteratorITCase.java
This fixes `mvn verify` for https://github.com/googlegenomics/dataflow-java/pull/124
We're in a middle place with auth and gRPC right now.  Regarding integration tests for gRPC:
* the ones in utils-java use a user credential which is currently the only way to auth for local runs.
* the ones in dataflow-java use the application default credential and run on Google Compute Engine.
My point is that we do have good integration test coverage, even though we have some constraints regarding the whitelist and api key support in gRPC for now.
=> Work around auth + whitelist issues.

CONTRIBUTING.rst
Local development
-----------------
With Maven you can locally install a SNAPSHOT version of the code, to use from other projects
directly without having to wait for the Maven repository. Use:
````
mvn install
````
to run the full tests and do a local install. You can also use
````
mvn install -DskipITs
````
to run only the unit tests and do a local install. This is faster.
=> mention skipITs

src/main/java/com/google/cloud/genomics/utils/GenomicsUtils.java, src/main/java/com/google/cloud/genomics/utils/Paginator.java, src/main/java/com/google/cloud/genomics/utils/ShardBoundary.java, src/main/java/com/google/cloud/genomics/utils/ShardUtils.java, src/main/java/com/google/cloud/genomics/utils/grpc/Example.java, src/main/java/com/google/cloud/genomics/utils/grpc/ReadStreamIterator.java, src/main/java/com/google/cloud/genomics/utils/grpc/VariantStreamIterator.java, src/test/java/com/google/cloud/genomics/utils/PaginatorTest.java, src/test/java/com/google/cloud/genomics/utils/ShardBoundaryTest.java, src/test/java/com/google/cloud/genomics/utils/ShardUtilsITCase.java, src/test/java/com/google/cloud/genomics/utils/ShardUtilsTest.java, src/test/java/com/google/cloud/genomics/utils/grpc/ReadStreamIteratorITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/VariantStreamIteratorITCase.java
Also added placeholder parameter for future support for partial responses so that when support is added, clients will not need to update method signatures.
After this pull request, I think this refactor is at a good stopping point to merge to master.
=> Enforce shard boundaries for gRPC.

README.md
@dloy please take a look
@jean-philippe-martin it might be helpful if you add similar instructions for intelliJ?
=> Add a note for Eclipse users and local builds.

src/main/java/com/google/cloud/genomics/utils/grpc/GenomicsChannel.java, src/test/java/com/google/cloud/genomics/utils/IntegrationTestHelper.java, src/test/java/com/google/cloud/genomics/utils/grpc/ReadStreamIteratorITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/VariantStreamIteratorITCase.java
Closes https://github.com/googlegenomics/utils-java/issues/51
API Key must come from a whitelisted project.  If not, the error is "io.grpc.StatusRuntimeException: NOT_FOUND: Method not found." as expected.
=> Use an API Key for gRPC integration tests.

src/main/java/com/google/cloud/genomics/utils/GenomicsUtils.java, src/main/java/com/google/cloud/genomics/utils/ShardUtils.java, src/test/java/com/google/cloud/genomics/utils/GenomicsUtilsITCase.java, src/test/java/com/google/cloud/genomics/utils/IntegrationTestHelper.java, src/test/java/com/google/cloud/genomics/utils/ShardUtilsITCase.java, src/test/java/com/google/cloud/genomics/utils/ShardUtilsTest.java
Take a look at https://github.com/deflaux/dataflow-java/commit/33f0cfffd0a500b63ff2d4f9e1640b0488921de0 so see how this change could be used downstream. (but I plan to refactor that refactor; it needs a bit more work)
=> Shard readGroupSets using the associated referenceSet.

src/main/java/com/google/cloud/genomics/utils/VariantUtils.java, src/main/java/com/google/cloud/genomics/utils/grpc/VariantUtils.java, src/test/java/com/google/cloud/genomics/utils/TestHelper.java, src/test/java/com/google/cloud/genomics/utils/VariantUtilsTest.java, src/test/java/com/google/cloud/genomics/utils/grpc/VariantUtilsTest.java
Also add v1 equivalents as needed.
Note that this goes along with:
* add a v1 version of  JoinNonVariantSegmentsWithVariants https://github.com/deflaux/dataflow-java/commit/d3949e045941ffab9f01127eecfd49e7060e1a6e
* port variant transformation pipeline to gRPC https://github.com/deflaux/codelabs/commit/dc0e0f26404463b3fe8e37090f369d01a65b3756 which will stay in a branch until gRPC is no longer behind a whitelist
=> Move VariantUtils from dataflow-java to utils-java.

src/main/java/com/google/cloud/genomics/utils/grpc/GenomicsStreamIterator.java, src/main/java/com/google/cloud/genomics/utils/grpc/ReadStreamIterator.java, src/main/java/com/google/cloud/genomics/utils/grpc/VariantStreamIterator.java, src/test/java/com/google/cloud/genomics/utils/grpc/ReadStreamIteratorITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/VariantStreamIteratorITCase.java
The current variants and reads integration tests pass.  Next step is to add additional tests for the retries before this can be merged to master.
Note that in all cases it currently creates a new iterator (sends a new Streaming request) upon retry.  It does not currently re-create the stub or the channel for certain status codes.  Those specific changes can be made if certain status codes correspond to failures that require more mitigation.
=> Add retrying of gRPC streams.

pom.xml, src/main/java/com/google/cloud/genomics/utils/grpc/Example.java, src/main/java/com/google/cloud/genomics/utils/grpc/GenomicsChannel.java, src/main/java/com/google/cloud/genomics/utils/grpc/GenomicsStreamIterator.java, src/main/java/com/google/cloud/genomics/utils/grpc/ReadStreamIterator.java, src/main/java/com/google/cloud/genomics/utils/grpc/VariantStreamIterator.java, src/test/java/com/google/cloud/genomics/utils/IntegrationTestHelper.java, src/test/java/com/google/cloud/genomics/utils/grpc/FaultyGenomicsServerITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/FaultyGenomicsServerITLongCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/GenomicsStreamIteratorRetryTest.java, src/test/java/com/google/cloud/genomics/utils/grpc/GenomicsStreamIteratorTest.java, src/test/java/com/google/cloud/genomics/utils/grpc/ReadStreamIteratorITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/TestHelper.java, src/test/java/com/google/cloud/genomics/utils/grpc/VariantStreamIteratorITCase.java
The main code changed a bit to make it easier to pass in the channel created by the [AbstractTransportTest](https://github.com/grpc/grpc-java/blob/master/interop-testing/src/test/java/io/grpc/testing/integration/InProcessTest.java) but otherwise this is mostly new tests.
Added:
* unit tests for shard boundaries (previously there were only integration tests)
* unit tests for retries
* integration tests for retries
* and a long running integration test for retries
=> Added tests for gRPC retries.

src/main/java/com/google/cloud/genomics/utils/grpc/VariantUtils.java, src/test/java/com/google/cloud/genomics/utils/grpc/VariantUtilsTest.java
This is needed for the port of Dataflow pipeline Identity-by-State to gRPC.
=> Add V1 version of call comparator.

src/main/java/com/google/cloud/genomics/utils/CredentialFactory.java, src/main/java/com/google/cloud/genomics/utils/GenomicsFactory.java, src/main/java/com/google/cloud/genomics/utils/GenomicsUtils.java, src/main/java/com/google/cloud/genomics/utils/OfflineAuth.java, src/main/java/com/google/cloud/genomics/utils/ShardUtils.java, src/main/java/com/google/cloud/genomics/utils/grpc/Example.java, src/main/java/com/google/cloud/genomics/utils/grpc/GenomicsChannel.java, src/main/java/com/google/cloud/genomics/utils/grpc/ReadStreamIterator.java, src/main/java/com/google/cloud/genomics/utils/grpc/VariantStreamIterator.java, src/test/java/com/google/cloud/genomics/utils/GenomicsFactoryITCase.java, src/test/java/com/google/cloud/genomics/utils/GenomicsFactoryTest.java, src/test/java/com/google/cloud/genomics/utils/GenomicsUtilsITCase.java, src/test/java/com/google/cloud/genomics/utils/IntegrationTestHelper.java, src/test/java/com/google/cloud/genomics/utils/OfflineAuthITCase.java, src/test/java/com/google/cloud/genomics/utils/OfflineAuthTest.java, src/test/java/com/google/cloud/genomics/utils/ShardUtilsITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/FaultyGenomicsServerITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/FaultyGenomicsServerITLongCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/ReadStreamIteratorITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/VariantStreamIteratorITCase.java
* Use Application Default Credentials by default for both the Genomics REST and gRPC APIs.
* Refactor GenomicsFactory to extract credential creation and OfflineAuth to separate files since that logic is also used by gRPC.
* Remove API key support in gRPC now that authentication is required.
=> Refactor Auth.

src/main/java/com/google/cloud/genomics/utils/Contig.java, src/main/java/com/google/cloud/genomics/utils/ShardBoundary.java, src/main/java/com/google/cloud/genomics/utils/grpc/VariantStreamIterator.java, src/test/java/com/google/cloud/genomics/utils/ShardBoundaryTest.java
This PR goes along with https://github.com/googlegenomics/dataflow-java/pull/182
=> Add shard boundary mode for overlapping non-variant segments.

pom.xml, src/main/java/com/google/cloud/genomics/utils/ShardBoundary.java, src/main/java/com/google/cloud/genomics/utils/VariantUtils.java, src/main/java/com/google/cloud/genomics/utils/grpc/GenomicsChannel.java, src/main/java/com/google/cloud/genomics/utils/grpc/GenomicsStreamIterator.java, src/main/java/com/google/cloud/genomics/utils/grpc/ReadStreamIterator.java, src/main/java/com/google/cloud/genomics/utils/grpc/VariantStreamIterator.java, src/main/java/com/google/cloud/genomics/utils/grpc/VariantUtils.java, src/test/java/com/google/cloud/genomics/utils/ShardBoundaryTest.java, src/test/java/com/google/cloud/genomics/utils/VariantUtilsTest.java, src/test/java/com/google/cloud/genomics/utils/grpc/ReadStreamIteratorITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/VariantStreamIteratorITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/VariantUtilsTest.java
Fixes https://github.com/googlegenomics/utils-java/issues/48
Also
* Handle another type of non-variant segment.
* Bump grpc dependency.
=> Finish client-side support for partial responses.

src/main/java/com/google/cloud/genomics/utils/CallSetUtils.java, src/main/java/com/google/cloud/genomics/utils/Contig.java, src/main/java/com/google/cloud/genomics/utils/GenomicsUtils.java, src/main/java/com/google/cloud/genomics/utils/ShardUtils.java, src/test/java/com/google/cloud/genomics/utils/CallSetUtilsTest.java, src/test/java/com/google/cloud/genomics/utils/ContigTest.java, src/test/java/com/google/cloud/genomics/utils/GenomicsUtilsITCase.java, src/test/java/com/google/cloud/genomics/utils/IntegrationTestHelper.java, src/test/java/com/google/cloud/genomics/utils/ShardUtilsITCase.java, src/test/java/com/google/cloud/genomics/utils/ShardUtilsTest.java, src/test/java/com/google/cloud/genomics/utils/grpc/FaultyGenomicsServerITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/FaultyGenomicsServerITLongCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/GenomicsStreamIteratorTest.java, src/test/java/com/google/cloud/genomics/utils/grpc/ReadStreamIteratorITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/VariantStreamIteratorITCase.java
This allows pipelines to be run on a subset of callsets.
=> Update streaming requests to be created from a prototype.

src/main/java/com/google/cloud/genomics/utils/ShardBoundary.java, src/main/java/com/google/cloud/genomics/utils/VariantUtils.java, src/main/java/com/google/cloud/genomics/utils/grpc/MergeAllVariantsAtSameSite.java, src/main/java/com/google/cloud/genomics/utils/grpc/MergeNonVariantSegmentsWithSnps.java, src/main/java/com/google/cloud/genomics/utils/grpc/MergeNonVariantSegmentsWithVariants.java, src/main/java/com/google/cloud/genomics/utils/grpc/VariantMergeStrategy.java, src/main/java/com/google/cloud/genomics/utils/grpc/VariantStreamIterator.java, src/main/java/com/google/cloud/genomics/utils/grpc/VariantUtils.java, src/test/java/com/google/cloud/genomics/utils/ShardBoundaryTest.java, src/test/java/com/google/cloud/genomics/utils/VariantUtilsTest.java, src/test/java/com/google/cloud/genomics/utils/grpc/MergeAllVariantsAtSameSiteITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/MergeAllVariantsAtSameSiteTest.java, src/test/java/com/google/cloud/genomics/utils/grpc/MergeNonVariantSegmentsWithSnpsITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/MergeNonVariantSegmentsWithSnpsTest.java, src/test/java/com/google/cloud/genomics/utils/grpc/MergeNonVariantSegmentsWithVariantsITCase.java, src/test/java/com/google/cloud/genomics/utils/grpc/MergeNonVariantSegmentsWithVariantsTest.java, src/test/java/com/google/cloud/genomics/utils/grpc/VariantMergeStrategyTestHelper.java, src/test/java/com/google/cloud/genomics/utils/grpc/VariantUtilsTest.java
Also:
* Don't assume the merge strategy is receiving data already in order.  This will not be true when the collection passed was created by a GroupByKey instead of pulled directly from the Variants API.
* Revert back to prior definition of non-variant segment and treat records with 'NON_REF' and additional values in alternate bases as variants (because sometimes they are variants).
* Remove obsolete Shard Boundary predicate.
=> Modify the variant merge strategies to be aware of the window.

src/main/java/com/google/cloud/genomics/utils/ReadUtils.java, src/main/java/com/google/cloud/genomics/utils/grpc/ReadUtils.java
The behavior of `ReadUtils` without this fix is undefined. However, it is very likely to cause tag unmarshalling failures when used concurrently, e.g. `htsjdk.samtools.SAMFormatException: Tag of type i should have signed decimal value`.
=> Avoid reuse of stateful static TextTagCodec - fixes concurrent use

src/main/java/com/google/cloud/genomics/utils/grpc/ReadUtils.java
In practice these values have different semantics. In the Readstore API, the `readGroupId` is a server-generated ID which corresponds to a read group that the user imported. Every Read in the Readstore belongs to a read group, meaning that even if the original caller imported reads without a read group, we would allocate a new one for them.
This "RG" tag will already be set everywhere we would want to consume it downstream.
=> Don't set the RG tag using read.getReadGroupId()
